# integrations/commands/help_command.py
from .base_command import BaseCommand

class HelpCommand(BaseCommand):
    """
    Comando para /ajuda. Retorna a mensagem de ajuda com os comandos disponíveis.
    """
    def execute(self) -> str:
        return (
            "🤖 *Assistente Virtual PDV* 🤖\n\n"
            "Aqui estão os comandos que você pode usar:\n\n"
            "💳 *FIADOS (CONTAS A RECEBER)*\n"
            "  `*/fiados`* - Lista os fiados pendentes (com ID).\n"
            "  `*/fiado pago <ID do fiado>`* - Marca um fiado como pago.\n"
            "  `*/fiado detalhes <nome do cliente>`* - Mostra detalhes dos fiados de um cliente.\n"
            "  `*/fiado criar \"Nome Cliente\" <valor>`* - Cria um novo fiado.\n"
            "  `*/fiado editar <ID> <novo valor>`* - Edita o valor de um fiado.\n"
            "  `*/fiado cancelar <ID>`* - Cancela um fiado.\n\n"
            "📈 *DASHBOARD*\n"
            "  `*/dashboard`* - Resumo completo do dia.\n\n"
            "📊 *RELATÓRIOS*\n"
            "  `*/vendas <período>`* - Vendas do período (hoje, ontem, 7dias, etc.).\n"
            "  `*/produtos_vendidos <período>`* - Ranking de produtos mais vendidos.\n\n"
            "📦 *CAIXA*\n"
            "  `*/caixa status`* - Status detalhado do caixa atual.\n"
            "  `*/caixa fechar`* - Relatório de pré-fechamento.\n"
            "  `*/caixa sangria <valor> <motivo>`* - Registrar sangria.\n"
            "  `*/caixa suprimento <valor> <motivo>`* - Registrar suprimento.\n\n"
            "📦 *PRODUTOS DE VENDA*\n"
            "  `*/produto consultar <nome/cód>`* - Detalhes de um produto de venda.\n"
            "  `*/produto alterar_preco <cód> <preço>`* - Altera o preço de um produto.\n\n"
            "🏭 *ESTOQUE (INSUMOS)*\n"
            "  `*/estoque grupos`* - Lista os grupos de estoque.\n"
            "  `*/estoque criar_grupo <nome>`* - Cria um novo grupo de estoque.\n"
            "  `*/estoque ver`* - Lista todos os itens em estoque.\n"
            "  `*/estoque add <cód> \"<nome>\" <grupo> <qtd> <unidade>`* - Adiciona item ao estoque.\n"
            "  `*/estoque add ... ; ...`* - Adiciona múltiplos itens (separados por ;).\n"
            "  `*/estoque baixa <cód> <qtd>, <cód2> <qtd2>`* - Dá baixa em itens do estoque.\n"
            "  `*/estoque ajustar <cód> <nova_qtd>`* - Ajusta quantidade de um item.\n"
            "  `*/estoque baixo`* - Lista itens com estoque baixo.\n\n"
            "⚙️ *ADMINISTRAÇÃO*\n"
            "  `*/aviso <mensagem>`* - Envia um aviso para a tela do PDV e para os outros gerentes.\n"
            "  `*/gerente listar`* - Lista os gerentes.\n"
            "  `*/gerente adicionar <número>`* - Adiciona um gerente.\n"
            "  `*/gerente remover <número>`* - Remove um gerente.\n"
            "  `*/aviso_agendado`* - Gerencia avisos agendados (listar, agendar, remover).\n"
            "  `*/notificacoes <on/off>`* - Ativa/desativa notificações.\n\n"
            "🛠️ *SISTEMA*\n"
            "  `*/status`* - Status detalhado da integração WhatsApp com métricas e alertas.\n"
            "  `*/logs`* - Sistema avançado de logs com filtros e paginação.\n"
            "    `*/logs stats`* - Estatísticas resumidas dos logs.\n"
            "    `*/logs <nível> [linhas] [página] [busca] [data_ini] [data_fim]`* - Logs filtrados.\n"
            "    Níveis: ERROR, WARNING, INFO, DEBUG, CONNECTION, MESSAGE, AUDIT\n"
            "    Ex: `*/logs ERROR 20 1 erro_conexao`* (20 linhas, página 1, busca por 'erro_conexao')\n"
            "  `*/backup`* - Inicia o backup do banco de dados.\n"
            "  `*/sistema limpar_sessao`* - Reinicia a conexão com o WhatsApp.\n\n"
            "🎉 *DIVERSÃO E ENGAGEMENT*\n"
            "  `*/sorteio funcionarios`* - Sorteia um funcionário aleatoriamente.\n"
            "  `*/sorteio clientes`* - Sorteia um cliente aleatoriamente.\n"
            "  `*/sorteio <lista>`* - Sorteia da lista fornecida (João, Maria, Pedro).\n"
            "  `*/quiz`* - Quiz rápido sobre produtos e empresa.\n"
            "  `*/palavra_do_dia`* - Palavra motivacional diária.\n"
            "  `*/meme`* - Meme motivacional aleatório.\n"
            "  `*/conselho`* - Conselho aleatório do dia para o negócio.\n"
            "  `*/elogio`* - Elogio motivacional aleatório para a equipe.\n"
            "  `*/frase`* - Frase motivacional famosa aleatória.\n"
            "  `*/motivacao`* - Mensagem motivacional para energizar o dia.\n"
            "  `*/piada`* - Piada leve para aliviar o dia.\n"
            "  `*/aniversario`* - Lembretes de aniversários da equipe.\n"
            "  `*/cumprimento`* - Cumprimento personalizado baseado no horário.\n"
            "  `*/clima [cidade] [estado]`* - Previsão do tempo (ex: `/clima Bitupitá CE`).\n"
            "  `*/dolar`* - Cotação atual do dólar.\n"
            "  `*/noticia`* - Notícias reais do setor varejista (quando disponível).\n\n"
            "ℹ️ Digite um comando para começar!"
        )
